### ISSUE TITLE
Options 13-17 not working

### ISSUE THREAD

**Issue by Mols1993** [r00t-3xp10it/morpheus#1]
Options 13-17 are not working ("X": is not a valid option), according to the .sh, they seem to be lacking an implementation, it looks like 13 actually has an implementation but it's not linked to the menu, if that is the case, maybe they shouldn't be there as valid options yet?

**Comment by r00t-3xp10it** [comment]
<br />

It's not my fault (that webpages are publishing a **non-finished** tool)....
because i have warned before that this project its on develop stage (not finished)...

The reason why the menu its build that way, its because i have started the work
by **writing the filters first** (I already had an idea of what I wanted to show)
and later then i have start the writing of the main tool around that plans..

<br /><br />

> hint:
    This tool main objective it's not to provide an easy way to exploit/sniff targets..
    but ratter a 'Call of attention' to tcp/udp manipulation technics (etter filters).
    "to inspire people to script, thats the reason for the existense of option[W] in the main menu"

<br />

`All filters in the tool, are just to demonstrate what kind of things can be achieved...`
i belive that the most funny step, it will be when you write your own filter and watch it run :+1:

**Comment by spiritedwolf** [comment]
@r00t-3xp10it i thought you have done with this module.

**Comment by spiritedwolf** [comment]
Remember we were trying it, you said it working fine at your end.
