### ISSUE TITLE
Problem with this (ERROR : 12, Cannot allocate memory)

### ISSUE THREAD

**Issue by rielinux** [r00t-3xp10it/morpheus#11]
Hi there, i have some issue, need your help. After 3 minutes using morpheus everything normal, but 
after that i receive notification like this:
1. Corrupt JPEG data: 29 extraneous bytes before marker 0xd6
Unsupported marker type 0xac
[driftnet] warning: driftnet-58a3c9120b03e0c6.jpeg: bogus image (err = 4)

2. ERROR : 12, Cannot allocate memory
[/build/ettercap-bGminI/ettercap-0.8.2/src/ec_threads.c:ec_thread_new_detached:210]

 not enough resources to create a new thread in this process: Operation not permitted 

note: ( i already have a newest ettercap) 
Thanks...

**Comment by r00t-3xp10it** [comment]
Hello brother that meens that you are using **option [7] - capture pictures**...
This report show me that you have errors in **driftnet and ettercap** (morpheus back-end appl)...

<br />

But wile in **driftnet** software the error its **normal** because the software **Cannot** handle all images...
`Corrupt JPEG data: 29 extraneous bytes before marker 0xd6`

In **ettercap** case it show me that your computer (PC) does not have many **free RAM available**...
`Cannot allocate memory - not enough resources to create a new thread in this process`
morpheus triggers **driftnet and ettercap** in the same thread (**process**)...

<br />

### Soluction?
    Try to stop all non-importante process from running in RAM
    before using morpheus or ettercap framework (using a cleanner?)

Correct me if iam wrong, have fun..

**Comment by rielinux** [comment]
Thank you for your reply and answer, I appreciate it... #caseclosed
