### ISSUE TITLE
Change images

### ISSUE THREAD

**Issue by prvsousa** [r00t-3xp10it/morpheus#12]
I use this tool to try to change images in the local lan but it doesn't work. It doesn't replace any image... You know what could be the error?

**Comment by r00t-3xp10it** [comment]
<br />

The truth is that this machine (**morpheus**) its outdated, because this methods
have worked a long time ago, with recent browser security features most of this
attacks sometimes fails ..

    And replacing images its one of the most difucults because it depends
    of image size (mb) and the modification of the tcp packet size to match
    the image size, so replacing images will only replace the correct ones
    (the rigth size - that allow us to not modifie tcp packet size also)..

It does not work as good as espected (this days) but for sometime that
iam planing to show ettercap filters to people, Its my bad was taken so
many years before writing this tool (i should have writen this 4 years ago) ..

<br />

**This are the images that are replaced in webpage .**.
![replace images](https://i2.wp.com/www.drchaos.com/wp-content/uploads/2017/01/morpheus-16.png?resize=502%2C346)
`Also remmenber that all this technics only works in HTTP (not https)`

<br />

**Replacing images (dr chaos):**
http://www.drchaos.com/morpheus-man-in-the-middle-security-tool/

<br />

**Comment by prvsousa** [comment]
This image is recent? I can't reproduce this

**Comment by r00t-3xp10it** [comment]
I know its hard to find a webpage http
and the images corret size to be replaced
and no-security browser measures ..

`but that screenshot was taken in: 06 Jan 2017 (dr chaos article)` ..

But botton line its that morpheus should be writen 4 years ago and not now..
there are other softwares (https) to achieve tcp/udp packet manipulation like
i try to show using ettercap ..

**Comment by prvsousa** [comment]
Ok. Thanks!
