### ISSUE TITLE
I found a bug of morpheus in Kali linux 

### ISSUE THREAD

**Issue by merlinnusr** [r00t-3xp10it/morpheus#15]
morpheus always overwrite the file  /etc/ettercap/etter.conf  when it start 

I uncomment this lines 

  redir_command_on = "iptables -t nat -A PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"
   redir_command_off = "iptables -t nat -D PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"

but when i start morpheus it always comment all the lines , i notice this because the script always display this message 

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 0 EGID 0...

**Comment by r00t-3xp10it** [comment]
**morpheus tool does not need 'port-forward' to work..**
the tool as writen to work on local lan (no ip-tables configuration needed)

<br />

### explaination of morpheus configuration settings:

    1 - morpheus will config ettercap to run with 'root' privs
          Privileges dropped to EUID 0 EGID 0... 
          (euid 0 and egid 0 == root privs)

    2 - morpheus dosent require port-forward to work
          SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
          (this SSL message its the default display warning for us to activate the port-forward tecnic if needed)

<br />

### Final notes:
dont worry with the SSL disectors warning..
because morpheus will not use those settings, even if you activate it on etter.conf file ..

**but thanks for reporting ..have fun ..**
