### ISSUE TITLE
How could I sniff information from outside my router ? May I sniff from the ISP ? 

### ISSUE THREAD

**Issue by engmed200577** [r00t-3xp10it/morpheus#23]
Hi , I wish I could sniff from my Internet Service Provider . Could I do that by this tool ? and How can I connect my router ? I receive the internet through an Lite Beam Device and then distribute the internet by router . How could I sniff from the ISP using above devices ?

**Comment by r00t-3xp10it** [comment]
### interesing question ..

The last option (**HTTP tcp Header Information Gathering Module**) that i have added to morpheus
allow us to capture http headers from **outside** to **inside** local lan .. but thats the only one.
https://github.com/r00t-3xp10it/morpheus/wiki/HTTP-tcp-Header-Information-Gathering-Module

Remmenber that morpheus depends of **MITM** (Man-In-The-Middle) to sniff, and mitm **does not** work outside local lan, because it depends of poising the arp cache of devices to be able to sniff/redirect traffic.
