### ISSUE TITLE
Bad Text formate

### ISSUE THREAD

**Issue by katesaikishore** [r00t-3xp10it/morpheus#26]
\033[34m    VERSION:\033[33m2.3\033[34m DISTRO:\033[33mKali\033[34m IP:\033[33m172.16.221.1\033[34m INTERFACE:\033[33meth0\033[34m IPv6:\033[33mACTIVE\033[34m

I am getting this type of text formate how to overcome this?

**Comment by r00t-3xp10it** [comment]
what **Shell** are you using ??? its not the default **sh** (bash) shell rigth ??
Because that type of errors appers if i change the shebang on top of my tool
from **sh** to **bash** <--- the tool its written to interact with default sh shell not with bash ..

#### Remark: sh and bash are diferent shells ...
`#!/bin/bash` <---- bash shebang
`#!/bin/sh` <---- sh shebang
