### ISSUE TITLE
 9    -  Replace website images 

### ISSUE THREAD

**Issue by Nomed1478963** [r00t-3xp10it/morpheus#7]
you forget number 9 in the code

case $choice in
1) sh_stage1 ;;
2) sh_stage2 ;;
3) sh_stage3 ;;
4) sh_stage4 ;;
5) sh_stage5 ;;
6) sh_stage6 ;;
7) sh_stage7 ;;
8) sh_stage8 ;;
9) sh_stage9 ;; :dagger: 
10) sh_stage10 ;;
11) sh_stage11 ;;
W) sh_stageW ;;

**Comment by r00t-3xp10it** [comment]
<br />

**_Nop, I did not forget_ ..**. :yum: 
The project its still in develop stage (means that iam currently writing funtions)...
And that funtion (option 9) its not yet tested/finished, thats the reason why i dont have
added the option 9 to the main menu, like i I did not have added options 12 and 13 :gear: ...


**Since many people are downloading a not finished tool, i has forced to do that..
To stop people from runing any un-finished funtions and then complain that the
funtions does not work (_have a little patience, this things [debugging] takes time_)...**

**Comment by Nomed1478963** [comment]
**ohh ok good job**  :facepunch:
